name: Playwright Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright pytest-html
          playwright install --with-deps

      - name: Debug environment
        run: |
          echo "=== Debug Info ==="
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Current dir: $(pwd)"
          echo "Contents:"
          ls -R

      - name: Run Playwright tests
        run: |
          mkdir -p $GITHUB_WORKSPACE/test-results
          pytest $GITHUB_WORKSPACE/tests/ \
            --html=$GITHUB_WORKSPACE/test-results/report.html \
            --self-contained-html -v

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-results
          path: $GITHUB_WORKSPACE/test-results/
